Add search to multipass docs
canonical-web-and-design/multipass.run pull request #149
Opened 2021-03-09 16:15 UTC by carkod

## QA

- Go to https://multipass-run-149.demos.haus/docs and search something like "application", which usually yields a lot of results
- Make sure the next button works and you can also search in the results page

## Issues
Fixes #148

2021-03-09 16:15 UTC, webteam-app commented
Demo starting at https://multipass-run-149.demos.haus

2021-03-09 19:00 UTC, anthonydillon requested changes
Some comments in the code.

2021-03-10 09:38 UTC, carkod commented on templates/docs/search.html
> +              <li class="p-list__item is-ticked"><a href="https://discuss.kubernetes.io/c/general-discussions/microk8s/26">Visit the forum</a></li>
Done Thanks.

2021-03-10 09:52 UTC, carkod commented on templates/docs/search.html
> +        <input class="p-search-box__input" name="q" id="search-input" type="search" {% if query %}value="{{ query }}"{% endif %} placeholder="e.g. juju" />
Done.

2021-03-11 09:54 UTC, carkod commented
@anthonydillon sorry I think I put the wrong label, I still need a code review, thanks.

2021-03-11 14:19 UTC, anthonydillon approved these changes
LGTM :+1:

2021-03-11 14:20 UTC, merged